### ISSUE TITLE
Various keys are not counted by the game

### ISSUE THREAD

**Issue by flippette** [7thbeatgames/adofai#132] opened 2024-04-16 13:08 UTC
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

`flippette` on DIscord

### Summary

As per the title, some keys are not counted:

- Left Alt
- Left Super (Left Windows)
- Right Super (Right Windows)

### Version

v2.7.0

### Operating System (OS)

Linux

### Platform

Steam

### Device Info

PC

### Steps to Reproduce

1. Start the game
2. Press affected keys listed above
3. Observe that they don't do anything

### Expected Behavior

Inputs on affected keys should be registering

### Observed Behavior

...they aren't

### Reproduction Rate

100%

**Comment by gurglemurgle5** [comment] 2024-04-16 15:04
This isn't a bug, this is intended behavior. If I recall correctly, function keys also are intentionally ignored.

Maybe an option to allow those keys might be useful?

(Note: I am not a dev)

**Comment by authop** [comment] 2024-04-22 01:23
Some of the system-reserved keys are escaped by default. As this is an expected behavior, I'm marking this as Close.

But you may always remap your system keys by using Microsoft Powertoys(Windows), keyd(Linux), or Karabiner(macOS).

**Closed by authop** 2024-04-22 01:23 UTC
Labels: Bug, Comp: In-game, Comp: QoL, Priority: Low
